### ISSUE TITLE
/Path parameter not working

### ISSUE THREAD

**Issue by tnederlof19** [pimatic/pimatic-sysinfo#14]
Changing the path does not work, still the original path is used to read the values.

I'm running pimatic on an Orange-Pi and the temperature readings do work, however 1/1000th of the 'normal' Raspberry-Pi values. Therefore, I made a script that multiplies the value and directed the path to there, however still the 'old', small values are displayed. This also happens with other values than temperature.
/edit:  I now see that this is only supposed to be used for diskusage, it would be nice if it could also be used for other values. It also does not work for diskusage, it still uses the actual diskusage when I change it to my temperature-script.

**Comment by mwittig** [comment]
> Changing the path does not work, still the original path is used to read the values.

Works as designed (on master, recent changes to be released soon). Path must be the mount point path of the file system. Limitation: only one file-system can be monitored

>  I now see that this is only supposed to be used for diskusage, it would be nice if it could also be used for other values.
I don't see how the `path` could be applicable for the other attributes.
