### ISSUE TITLE
[Request] Set Uptime over 24h to "DD days HH hours"

### ISSUE THREAD

**Issue by tehmilcho** [pimatic/pimatic-sysinfo#15]
Hi,

it is possible to change the Uptime from the Sensor to after 24hours show Days and Hours? In the Moment it will just show the hours but  "83:31:44" (for example) is not really useful. 

Greetings Milcho

**Comment by mwittig** [comment]
Hi Milcho, 

This is more of an issue of the pimatic frontend on how data objects are rendered. The plugin provides the uptime in seconds. Please check the forum for post on the matter. 

A possible workaround I another attribute with a duration string created by a function along the lines of <https://stackoverflow.com/questions/28705009/how-do-i-get-the-server-uptime-in-node-js>. If you nknow a better package which could be used please let me know.

Greetings,
Marcus

**Comment by mwittig** [comment]
The next release of the frontend will include an uptime formatter
