### ISSUE TITLE
Memory Usage shows totally different values than Taskmanager

### ISSUE THREAD

**Issue by akicker** [pimatic/pimatic-sysinfo#19]
Sysinfo 0.9.5 shows about double values (M USED) than taskmanager, ... 
![image](https://user-images.githubusercontent.com/22791890/55276060-00777180-52ef-11e9-8fab-cd8f059b733b.png)

**Comment by mwittig** [comment]
Memory usage on Linux is capture by fetching data from `/proc/meminfo`. Can you please post a `cat /proc/meminfo`and a screenshot of the figures shown in the Taskmanager at the same time? Thanks!

**Comment by akicker** [comment]
hi, meminfo shows:
![image](https://user-images.githubusercontent.com/22791890/55288425-d938a700-53b7-11e9-8b6b-97c58f13e4ba.png)
stepping back to Sysinfo 0.9.4 shows more plausible values!

**Comment by akicker** [comment]
... one more info using the command free ... used total matches with taskman ;-)
![image](https://user-images.githubusercontent.com/22791890/55289699-3b020c80-53ca-11e9-8970-9bc930d82570.png)

**Comment by mwittig** [comment]
Thanks. The difference is that TaskManager shows MemAvailable instead of MemFree. MemAvailable is an estimation of  MemFree plus reclaimable memory (buffers and cache). 

```
// |------------------------------------------------------------|
// |                           R A M                            |
// |______________________|_____________________________________|
// |                      |      available (6) estimated        |
// |______________________|_________________________|___________|
// |     active (2)       |   buffers/cache (5)     | free (3)  |
// |________________________________________________|___________|
// |                          total (1)                         |
// |____________________________________________________________|
//
// Reference: http://www.software-architect.net/blog/article/date/2015/06/12/-826c6e5052.html

**Comment by akicker** [comment]
OK, the issue is how **used** is defined ;-)
in the previous version 0.9.4 **memory** was defined as res.total - res.avail
see: ../node_modules/pimatic-sysinfo/sysinfo.coffee
now 0.9.5 you are showing **usedMemory** as res.used (looks like total - free)
raspbian **taskman** shows: memory consumption (total- avail)
command **free** uses: used = total - free - buffers - cache
command **top** shows similar values as free
I think the old definition (total-avail) says more on the health of the system!

**Comment by mwittig** [comment]
> I think the old definition (total-avail) says more on the health of the system!

I agree with this and will change the values for memoryUsed (= Active) and memoryFree (= Available) with the next release.

**Comment by akicker** [comment]
Great, working perfect now 👍

**Comment by mwittig** [comment]
Excellent! I am closing this now.
