### ISSUE TITLE
System running time

### ISSUE THREAD

**Issue by Nears** [pimatic/pimatic-sysinfo#4]
I just was wondering if it is easy to add the information how long the system running or how long a network connection exists or any other lets call them runtimes.

Is there an easy way to get this information? It would be great an could be used perfectly for so e rules I am thinking about.

**Comment by Nears** [comment]
Just had a little walk around in  the pimatic framework and saw that shell-execute plugin has the possibility to be used as sensor. I will try this later on, i hope it will do the job.

**Comment by sweetpi** [comment]
Done, thanks to @mwittig.
