### ISSUE TITLE
Variables with wrong color

### ISSUE THREAD

**Issue by pimagical** [pimatic/pimatic-sysinfo#7]
Disk and database variables are gray colored and should be black
![image](https://cloud.githubusercontent.com/assets/11790664/7444614/ad894d0e-f18b-11e4-98fd-11cd4a994be6.jpg)

**Comment by sweetpi** [comment]
The gray color indicates that the value wasn't updated for some time. Maybe it should be relative to the configurated interval.

**Comment by pimagical** [comment]
Sorry for my misunderstanding

**Comment by sweetpi** [comment]
No worries, I think it would be a good idea to make the gray out time more dynamic.

**Comment by pimagical** [comment]
Dynamic gray out time is a result of when it is relative to the configured interval?

Brainstorming:
- A gray out value in red color update info when it couldnt get the values at the selected interval time? Like a heartbeat.
- A xAttributeOptions updateInfo to show not show?

**Comment by mwittig** [comment]
I am closing this here as the general problem is solved as far as I can see. I'll take the "brainstorming" bits and create a feature request for this.

https://forum.pimatic.org/topic/4646/configurable-time-out-for-values-which-have-not-been-updated-configurable-color
