### ISSUE TITLE
sysinfo device can't be deleted in gui

### ISSUE THREAD

**Issue by betz0r** [pimatic/pimatic-sysinfo#9]
titles says, can't delete the device by pulling it to bottom red delete-box. i even can't resort it in my list, it just stays at the bottom. doesn't happen with other devices.

edit: the device is NOT listed in the "pages" object but displayed on the page in the gui?

**Comment by sweetpi** [comment]
Should be fixed in the latest release of the mobile frontend. Please reopen if the problem still exists.

**Comment by betz0r** [comment]
bug still persists with latest updates, not movable from bottom of page or deleteable. shall i provide u any debug information?
